apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  labels:
    app: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
        - name: vault
          image: hashicorp/vault:latest
          ports:
            - containerPort: 8200
          env:
            - name: VAULT_DEV_ROOT_TOKEN_ID
              value: 'root'
            - name: VAULT_DEV_LISTEN_ADDRESS
              value: '0.0.0.0:8200'
          command:
            - 'server'
            - '-dev'
            - '-dev-root-token-id=root'
          volumeMounts:
            - name: vault-data
              mountPath: /vault/data
          securityContext:
            capabilities:
              add: ['IPC_LOCK']
      volumes:
        - name: vault-data
          persistentVolumeClaim:
            claimName: vault-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: vault
spec:
  selector:
    app: vault
  ports:
    - port: 8200
      targetPort: 8200
  type: ClusterIP
